extends RefCounted
class_name GameDefs

const STATION_REGISTER := "register"
const STATION_SINK := "sink"
const STATION_MAIN_TABLE := "main_table"
const STATION_SUB_TABLE := "sub_table"
const STATION_DISPLAY_FRIDGE := "display_fridge"
const STATION_PICKUP_COUNTER := "pickup_counter"

const ACTION_TAKE_ORDER := "take_order"
const ACTION_PREPARE_PACKAGING := "prepare_packaging"
const ACTION_ADD_ICE := "add_ice"
const ACTION_POUR_WATER := "pour_water"
const ACTION_POUR_SPARKLING_WATER := "pour_sparkling_water"
const ACTION_ADD_PREMADE_BASE := "add_premade_base"
const ACTION_DELIVER_ORDER := "deliver_order"
const ACTION_RESTOCK_SUPPLIES := "restock_supplies"
const ACTION_MEASURE_POWDER := "measure_powder"
const ACTION_DISSOLVE_POWDER := "dissolve_powder"
const ACTION_MEASURE_SYRUP := "measure_syrup"
const ACTION_POUR_MILK := "pour_milk"
const ACTION_PULL_ESPRESSO := "pull_espresso"
const ACTION_STEAM_MILK := "steam_milk"
const ACTION_PIPE_WHIPPED_CREAM := "pipe_whipped_cream"
const ACTION_ADD_TOPPING := "add_topping"
const ACTION_USE_MICROWAVE := "use_microwave"
const ACTION_USE_SMOOTHIE_MACHINE := "use_smoothie_machine"
const ACTION_FIX_BASIC_EQUIPMENT := "fix_basic_equipment"

const CATEGORY_COFFEE := "coffee"
const CATEGORY_TEA := "tea"
const CATEGORY_LATTE := "latte"
const CATEGORY_ADE := "ade"
const CATEGORY_POWDER := "powder"
const CATEGORY_SMOOTHIE := "smoothie"
const CATEGORY_DISPLAY := "display"
const CATEGORY_DESSERT := "dessert"

const PHASE_NORMAL := "normal"
const PHASE_PEAK := "peak"
const PHASE_CLOSING := "closing"

const SUPPLY_CUP := "cup"
const SUPPLY_LID := "lid"
const SUPPLY_SLEEVE := "sleeve"
const SUPPLY_HANDLE := "handle"
const SUPPLY_STRAW := "straw"
const SUPPLY_CARRIER := "carrier"
const SUPPLY_ICE := "ice"
const SUPPLY_MILK := "milk"
const SUPPLY_CREAM := "cream"
const SUPPLY_POWDER := "powder"
const SUPPLY_SYRUP := "syrup"
const SUPPLY_FRUIT_BASE := "fruit_base"
const SUPPLY_TEA := "tea"
const SUPPLY_DESSERT := "dessert"

const EQUIPMENT_ICE_MAKER := "ice_maker"
const EQUIPMENT_ESPRESSO_MACHINE := "espresso_machine"
const EQUIPMENT_FRIDGE := "fridge"
const EQUIPMENT_FREEZER := "freezer"
const EQUIPMENT_MICROWAVE := "microwave"
const EQUIPMENT_SMOOTHIE_MACHINE := "smoothie_machine"
